default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost
  port: 3306

development:
  <<: *default
  database: HrMitra_development

test:
  <<: *default
  database: HrMitra_test

production:
  <<: *default
  database: HrMitra_production
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: localhost
